Fixed broken indentation in pod.yaml
Line 8 of the nginx pod.yaml wasn't indented properly, which caused the following error to occur:

Admin:~/environment $ kubectl apply -f pod.yaml
error: error converting YAML to JSON: yaml: line 8: did not find expected key

Added 2 space indentation to line 8 to fix the yaml.